// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/blog.tsx";
import * as $1 from "./routes/blog/[id].tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Todo.tsx";
import * as $$2 from "./islands/TodoList.tsx";

const manifest = {
  routes: {
    "./routes/blog.tsx": $0,
    "./routes/blog/[id].tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Todo.tsx": $$1,
    "./islands/TodoList.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
